### PR TITLE
Fix sass-lint 1.6 final-newline rule issues

### LINKED ISSUE #627: Sass - Nested items at the end of the file doesn't register final new line
The following code will ignore the final new line and incorrectly flag up that a new line is required. This appears only to happen when the file ends with a nested node.

```sass
.foo
  content: 'foo'
  .bar
    content: 'bar'

```
Sass 1.5.1, develop branch

### LINKED ISSUE #630: Sass - Final new line flags if anything but block at end of fine
Currently if you require a final new line, sass-lint will flag it as missing if anything bar a block is at the end.

The following causes an error. All examples have a new line at the bottom of the file.

```sass
@import test

```
```sass
$foo: true

```
```sass
$bar: (
  baz: true
)

```

Sass 1.6, develop

### PR DESCRIPTION
**Pull request by bgriffith**
Fixes two issues with the final-newline rule and the sass syntax, that popped up after the update to 1.6.

Fixes #627 
Fixes #630 

DCO 1.1 Signed-off-by: Ben Griffith gt11687@gmail.com

### CODE REVIEW

File: lib/rules/final-newline.js [hunk 1]
```diff
@@ -2,29 +2,39 @@
 
 var helpers = require('../helpers');
 
+/**
+ * Get the 'last' node of the tree to test for an EOL
+ *
+ * @param {Object} node - The node who's last child we want to return
```
Comment (DanPurdy) [inline lib/rules/final-newline.js]: whose
