### PR TITLE
Fix issue with placeholder name format with interpolation

### LINKED ISSUE #625: Placeholder name format doesn't ignore variables
Current the `placeholder-name-format` rule will incorrectly flag up variables.
```scss
$var: 'foo';

%#{$var} {
  font-size: 18px;
}
```

Will incorrectly return `Placeholder %#{$var} should be written in lowercase with hyphens`.

Sass 1.5.1, develop branch

### PR DESCRIPTION
**Pull request by DanPurdy**
Fixes #625 

Makes sure that the placeholder name is an ident rather than interpolation or a variable etc.

`DCO 1.1 Signed-off-by: Dan Purdy <dan@danpurdy.co.uk>`

### CODE REVIEW

File: lib/rules/placeholder-name-format.js [hunk 1]
```diff
@@ -18,60 +18,60 @@ module.exports = {
...
-        break;
-      default:
-        if (!(new RegExp(parser.options.convention).test(strippedName))) {
-          violationMessage = 'Placeholder \'%' + name + '\' should match regular expression /' + parser.options.convention + '/';
 
-          // convention-message overrides violationMessage
-          if (parser.options['convention-explanation']) {
-            violationMessage = parser.options['convention-explanation'];
+        switch (parser.options.convention) {
+        case 'hyphenatedlowercase':
```
Comment (bgriffith) [inline lib/rules/placeholder-name-format.js]: Appears to be some weird indentation going on

Comment (DanPurdy) [inline lib/rules/placeholder-name-format.js]: Nope, It's how eslint is set.. Changing to how we would write it gives indentation warning, also travis is already doing the linting tests & you'll wanna do the PR with ?w=1 as i only added 2 lines..

Comment (bgriffith) [inline lib/rules/placeholder-name-format.js]: It's still weird haha
