### PR TITLE
Adjust no-trailing-zero to fail on first decimal

### LINKED ISSUE #438: New Rule: Unnecessary Mantissa
Name: `unnecessary-mantissa`

Add a rule that enforces that removal of all unnecessary trailing decimal points (e.g. `4.0` should be written as `4`).

I was a little ambitious and have already written the code to complete this as [`a7db54b`](https://github.com/Dru89/sass-lint/commit/a7db54b6b910e3f7ce6623a2c1d9eca7c5fcc017) but will wait to submit the pull request as per the contributing guidelines.

### LINKED ISSUE #439: Trailing zero issue
As discovered in #438 it seems that the `no-trailing-zero` rule only works correctly when there is at least one non zero number following a decimal point.

The following is currently valid.
```scss

foo {
  margin: 1.0000000000
}
```

The following is not

```scss

foo {
  margin: 1.10000000000
}
```

### PR DESCRIPTION
**Pull request by Dru89**
The `no-trailing-zero` rule was not failing on numbers like `1.0`, as the regular expression required there to be a non-zero number in the decimal for the check to work.  

This change removes that constraint and adds test cases to make sure that the result works as expected.  The change fixes #438 and fixes #439.

DCO 1.1 Signed-off-by: Drew Hays <drewshays@gmail.com>

### CODE REVIEW

**Comment by Dru89** [comment]
Welp, that was embarrassing.  I kept playing with the test cases to make sure that I felt everything was sufficiently covered, but forgot to commit the changes to the test file.  It should be updated now.

**Comment by benthemonkey** [comment]
LGTM :+1:

**Comment by DanPurdy** [comment]
Thanks for this!

**Comment by DanPurdy** [comment]
Yep, just checked it against some other values, all good to me, thanks @Dru89

File: lib/rules/no-trailing-zero.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 var helpers = require('../helpers');
 
-var trailingZeroRegex = /^(\d+\.|\.)+(\d*?[1-9])0+$/;
+var trailingZeroRegex = /^(\d+\.|\.)+(\d*?)0+$/;
```
Comment (bquorning) [inline lib/rules/no-trailing-zero.js]: I believe `^(\d+\.|\.)` could be changed to `^(\d*\.)` which in my opinion is a bit easier to read.
